import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { Inter, Outfit } from "next/font/google";

import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import NavbarWrapper from "@/components/NavbarWrapper";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className} `}>
          <Providers>
            <NavbarWrapper />
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
